### ISSUE TITLE
mario-more

### ISSUE THREAD

**Issue by Robs87** [mancuoj/CS50x#2]
为啥找你的抄作业，运行./mario.c老提示Permission denied

**Comment by mancuoj** [comment]
编译后运行
`make mario`
`./mario`

**Comment by mancuoj** [comment]
> 为啥找你的抄作业，运行./mario.c老提示Permission denied

`make mario`
`./mario`

**Comment by Robs87** [comment]
> > 为啥找你的抄作业，运行./mario.c老提示Permission denied
> 
> `make mario` `./mario`

感谢老哥，难怪之前运行make mario 没有成功的，最后一个printf没有分号，非要运行了vs自带的调试 才出现报错
