### ISSUE TITLE
关于Week7的fiftyville作业的疑惑

### ISSUE THREAD

**Issue by darkchaox** [mancuoj/CS50x#6]
ID 163目击者的证词如下：
| 163 | Raymond | 2021 | 7     | 28  | As the thief was leaving the bakery, **they called** someone who talked to them for less than a minute. In the call, I heard the thief say that **they were planning to take** the earliest flight out of Fiftyville tomorrow. The thief then asked the person on the other end of the phone to purchase the flight ticket. |

上面提到他们打电话给某人......他们准备坐明天最早一班飞机。如果这样推断，在犯罪现场的不应该至少两个人吗？坐飞机应该也是至少两个人？

**Comment by mancuoj** [comment]
我是按照排除法来做的，sql文件也有体现，毕竟有三段证词，不要在意细节🌚
